RPC_USER: "btcuser"
RPC_PASSWORD: "btcpass"
RPC_PORT: 8332
RPC_HOST: "localhost"
EXP_URL: "https://blockchain.info/q/getblockcount"
RETRY_MAX_COUNT: 3
RETRY_WAIT_TIME: 5
WEBHOOK_URL: "https://hooks.slack.com/services/xxxxxxxxx"